### ISSUE TITLE
fix examples for Jina==1.1

### ISSUE THREAD

**Issue by Yongxuanzhang** [jina-ai/examples#429]
- [x] multires-lyrics-search: this is because [#2141](https://github.com/jina-ai/jina/pull/2141) introduced breaking changes. will be fixed in ->https://github.com/jina-ai/jina-hub/pull/5789
- [x] tumblr-gif-search: same reason as [#2141](https://github.com/jina-ai/jina/pull/2141) -> https://github.com/jina-ai/examples/pull/431 https://github.com/jina-ai/examples/pull/434
- [x] audio-search: same reason as [#2141](https://github.com/jina-ai/jina/pull/2141)-> https://github.com/jina-ai/examples/pull/430
- [x] object-search is fixed since `single_multi_input` is fixed in Imagereader
- [x] pokedex-search is fixed since `single_multi_input` is fixed in Imagereader

The tumblr is failing in 1.0.12 probably because of https://github.com/jina-ai/jina/pull/2198, or other reasons maybe
