### ISSUE TITLE
add teaching comments to example YAML

### ISSUE THREAD

**Issue by FionnD** [jina-ai/examples#445]
### Feature Request 
Based on a request from the community, it was suggested that we could add comments to YAML examples to better explain what's happening where. 

- [ ] wikipedia-sentences #698
- [ ] multires-lyrics-search #698
- [ ] cross-modal-search #698
- [ ] query-while-indexing #665 

### Acceptance Criteria
This ticket is done when: Where possible, additionally comments have been added to the existing example YAML to show's what's happening. Please open a single PR with the suggestions and allow the dev role to review them as well.

**Comment by FionnD** [comment]
@rutujasurve94  Nan 'volunteered' you for this task, what do you think?

**Comment by theUnkownName** [comment]
I didn't see this before and the PR I made about updating [fashion-mnist](https://github.com/jina-ai/examples/pull/483/commits/f114232a208749a38dce8255e1c26f8e93bd7440) already takes care of its yaml files

**Comment by theUnkownName** [comment]
This is the [PR](https://github.com/jina-ai/examples/pull/498) for the other yaml files

**Comment by cristianmtr** [comment]
Can we tick the checkboxes in the main ticket description when a PR is merged?

**Comment by FionnD** [comment]
This issue is now being tracked in https://github.com/jina-ai/internal-tasks/issues/83

**Comment by jakob1111996** [comment]
Will work on this after #696
