### ISSUE TITLE
Update Examples to Jina 1.2 

### ISSUE THREAD

**Issue by FionnD** [jina-ai/examples#512]
Now that Jina 1.2 has been released, all our examples should be updated to work the latest release. 

Tasks: 
1. Run the example (Index and query) with Jina 1.2. Ensure that it runs without error. 
2. Update the requirements .txt file to version lock the example to 1.2 

- [x] Semantic Wikipedia Search #559 
- [x] Add incremental Indexing #571
- [x] Object detection #511, #598
- [x] Youtube audio search  #594 
- [x] Index & query with FAISS  #520
- [x] Cross Modal #623
- [x] Multi-modal #624
- [x] PDF search #593
- [x] Query Lang #574

----

-  Tumblr GIF [To be deleted]
-  Search lyrics [To be deleted]
-  Google Big Transfer with Pokemon [To be deleted]
